#!/bin/bash  

muted=0

while [ true ]
do
	if ! ./headphone-detector | grep "Headphones"
	    then
	        echo "Outside"
	        if ! curl --silent http://192.168.2.28:8080/sbar.html | grep Idle
	            then
					if [[ "$muted" == 0 ]]
						then
							currentVolume=`osascript -e "output volume of (get volume settings)"`
						fi
					muted=1
	                osascript -e "set Volume 1"
	                echo "Turn volume down"
				else
					if [[ "$muted" == 1 ]]
						then
							echo "Turn back up"
							osascript -e "set volume output volume $currentVolume"
					fi
					muted=0
			fi
	fi
	sleep 1
done